[ModuleConf]
gamepad = true
audio = true

[WindowMode]
width = 800.0
height = 600.0
maximized = false
fullscreen_type = FullscreenType::Windowed
borderless = false
min_width = 0.0
max_width = 0.0
min_height = 0.0
max_height = 0.0
resizable = false

[WindowSetup]
title = "A Rustically Guessing Game"
samples = NumSamples::Zero
vsync = true
icon = ""
srgb = true